name: Build APK with Buildozer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container: kivy/buildozer  # ✅ Готовый Docker-образ со всем нужным

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build APK
        run: |
          pip install --upgrade buildozer cython
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Shifra-APK
          path: bin/*.apk
