name: Build APK with Buildozer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      PATH: /usr/local/bin:${{ github.workspace }}/android-sdk/build-tools/33.0.2:${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:$PATH

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip tar wget openjdk-8-jdk python3-pip libffi-dev libssl-dev libsqlite3-dev
          pip install --upgrade pip
          pip install cython buildozer

      - name: Install Android SDK & Build Tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O sdk.zip
          unzip sdk.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest

          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
          sdkmanager --sdk_root=$ANDROID_HOME \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2"

          # Проверка aidl
          if [ -f "$ANDROID_HOME/build-tools/33.0.2/aidl" ]; then
            echo "✅ AIDL найден"
            sudo ln -s $ANDROID_HOME/build-tools/33.0.2/aidl /usr/local/bin/aidl
          else
            echo "❌ AIDL НЕ найден"
            exit 1
          fi

      - name: Build APK
        run: |
          which aidl || echo "⚠️ AIDL не найден в PATH"
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Shifra-APK
          path: bin/*.apk
