name: Build APK with Buildozer

on:
  push:
    branches:
      - main  # или твоя ветка

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies and Android SDK build tools
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-8-jdk python3-pip libffi-dev libssl-dev libsqlite3-dev
          pip install --upgrade pip
          pip install buildozer cython

          # Установка sdkmanager
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/cmdline-tools
          mkdir -p $HOME/Android/Sdk/cmdline-tools
          mv $HOME/cmdline-tools/cmdline-tools $HOME/Android/Sdk/cmdline-tools/latest

          export ANDROID_SDK_ROOT=$HOME/Android/Sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH

          # Принимаем лицензии и устанавливаем build-tools и platform-tools
          yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-33" "build-tools;33.0.2"

          # Проверка aidl
          ls $ANDROID_SDK_ROOT/build-tools/33.0.2/aidl

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Shifra-APK
          path: bin/*.apk
